packages:
  - 'packages/*'
  - 'examples/*'
  - 'benchmarks/*'
  - 'website'
  - '!examples/react18'
  - '!examples/react17'

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4