import type { RouteDef } from '../types'

/**
 * Convert a route path to a safe identifier name for generated code.
 */
function routePathToName(routePath: string): string {
  if (routePath === '/') return 'index'
  return routePath.replace(/^\//, '').replace(/[/:*]/g, '_').replace(/_+/g, '_')
}

/**
 * Normalize a file path to use forward slashes (for import statements).
 */
export function toImportPath(filePath: string): string {
  return filePath.replace(/\\/g, '/')
}

/**
 * Generate the server entry that delegates to the runtime handler.
 *
 * The generated code is minimal: imports, module map, route definitions,
 * and a call to createRequestHandler. All handler logic lives in the
 * runtime module (@paretojs/core/node).
 */
export function generateServerEntry(options: {
  routes: RouteDef[]
  clientEntryUrls?: string[]
  globalCssPaths?: string[]
  cssUrls?: string[]
  notFoundPath?: string
  errorPath?: string
  rootHeadPath?: string
  documentPath?: string
  routeManifest?: { routes: Record<string, unknown> }
  wkWebViewFlushHint?: boolean
}): string {
  const {
    routes,
    clientEntryUrls = [],
    globalCssPaths = [],
    cssUrls = [],
    notFoundPath,
    errorPath,
    rootHeadPath,
    documentPath,
    routeManifest,
    wkWebViewFlushHint = false,
  } = options

  // Collect all unique module paths and deduplicate imports
  const modulePathMap = new Map<string, string>()
  let moduleIndex = 0

  function ensureModule(filePath: string): string {
    const importPath = toImportPath(filePath)
    if (modulePathMap.has(importPath)) return modulePathMap.get(importPath)!
    const varName = `mod_${moduleIndex++}`
    modulePathMap.set(importPath, varName)
    return varName
  }

  // Register all module paths from routes
  for (const route of routes) {
    ensureModule(route.componentPath)
    if (route.loaderPath) ensureModule(route.loaderPath)
    for (const hp of route.headPaths) ensureModule(hp)
    for (const lp of route.layoutPaths) ensureModule(lp)
  }

  // Register not-found module if available
  if (notFoundPath) {
    ensureModule(notFoundPath)
  }

  // Register error module if available
  if (errorPath) {
    ensureModule(errorPath)
  }

  // Register root head module if available (used for 404/error pages)
  if (rootHeadPath) {
    ensureModule(rootHeadPath)
  }

  // Register document module if available (provides getDocumentProps)
  if (documentPath) {
    ensureModule(documentPath)
  }

  // Generate import statements
  const imports = Array.from(modulePathMap.entries()).map(
    ([importPath, varName]) => `import * as ${varName} from '${importPath}';`,
  )

  // Generate module map entries
  const moduleMapEntries = Array.from(modulePathMap.entries()).map(
    ([importPath, varName]) => `  '${importPath}': ${varName},`,
  )

  // Generate route definitions (RouteDef-compatible)
  const routeDefs = routes.map(route => {
    const optional = [
      route.loaderPath && `loaderPath: '${toImportPath(route.loaderPath)}'`,
    ]
      .filter(Boolean)
      .map(s => `    ${s},`)
      .join('\n')

    return `  {
    path: '${route.path}',
    pattern: ${route.pattern.toString()},
    paramNames: ${JSON.stringify(route.paramNames)},
    segments: ${JSON.stringify(route.segments)},
    componentPath: '${toImportPath(route.componentPath)}',
    layoutPaths: ${JSON.stringify(route.layoutPaths.map(toImportPath))},
    headPaths: ${JSON.stringify(route.headPaths.map(toImportPath))},
${optional}
    isDynamic: ${route.isDynamic},
    isCatchAll: ${route.isCatchAll},
    isResource: ${route.isResource},
  }`
  })

  // Global CSS imports (Vite handles CSS injection via module graph)
  const cssImports = globalCssPaths.map(p => `import '${toImportPath(p)}';`)

  return `// Auto-generated by @paretojs/core -- do not edit
import { createRequestHandler } from '@paretojs/core/node';
${imports.join('\n')}
${cssImports.length > 0 ? '\n' + cssImports.join('\n') : ''}

const moduleMap = {
${moduleMapEntries.join('\n')}
};

const routes = [
${routeDefs.join(',\n')}
];

export default createRequestHandler({
  routes,
  manifest: ${routeManifest ? JSON.stringify(routeManifest) : '{ routes: {} }'},
  requireModule: (p) => moduleMap[p],
  clientEntry: ${JSON.stringify(clientEntryUrls)},
  cssUrls: ${JSON.stringify(cssUrls)},${notFoundPath ? `\n  notFoundPath: '${toImportPath(notFoundPath)}',` : ''}${errorPath ? `\n  errorPath: '${toImportPath(errorPath)}',` : ''}${rootHeadPath ? `\n  rootHeadPath: '${toImportPath(rootHeadPath)}',` : ''}${documentPath ? `\n  documentPath: '${toImportPath(documentPath)}',` : ''}${wkWebViewFlushHint ? `\n  wkWebViewFlushHint: true,` : ''}
});
`
}

/**
 * Generate the unified client entry for SPA-style navigation.
 * Pages are lazy-loaded for code splitting. Layouts are eagerly imported
 * so the hydration tree matches the server-rendered HTML.
 */
export function generateUnifiedClientEntry(
  routes: RouteDef[],
  globalCssPaths: string[] = [],
  notFoundPath?: string,
  errorPath?: string,
): string {
  const lazyImports: string[] = []
  const routeMap: string[] = []

  // Collect unique layout paths and generate import statements
  const layoutPathMap = new Map<string, string>()
  let layoutIndex = 0
  for (const route of routes) {
    for (const lp of route.layoutPaths) {
      const importPath = toImportPath(lp)
      if (!layoutPathMap.has(importPath)) {
        const varName = `Layout_${layoutIndex++}`
        layoutPathMap.set(importPath, varName)
      }
    }
  }

  const layoutImports = Array.from(layoutPathMap.entries()).map(
    ([importPath, varName]) => `import ${varName} from '${importPath}';`,
  )

  // Import global CSS
  const cssImports = globalCssPaths.map(p => `import '${toImportPath(p)}';`)

  routes.forEach((route, i) => {
    if (route.isResource) return // Skip resource routes in client entry
    const varName = `page_${i}`
    const name = routePathToName(route.path)
    lazyImports.push(
      `const ${varName} = () => import('${toImportPath(route.componentPath)}');`,
    )

    const layouts = route.layoutPaths.map(
      lp => layoutPathMap.get(toImportPath(lp))!,
    )

    const headLoadersStr =
      route.headPaths.length > 0
        ? `, headLoaders: [${route.headPaths.map(hp => `() => import('${toImportPath(hp)}')`).join(', ')}]`
        : ''

    routeMap.push(
      `  { path: '${route.path}', load: ${varName}, name: '${name}', hasLoader: ${!!route.loaderPath || 'false'}, paramNames: ${JSON.stringify(route.paramNames)}, layouts: [${layouts.join(', ')}]${headLoadersStr} }`,
    )
  })

  const allImports = [...layoutImports]

  const notFoundImport = notFoundPath
    ? `import NotFoundComponent from '${toImportPath(notFoundPath)}';`
    : ''
  const errorImport = errorPath
    ? `import ErrorComponent from '${toImportPath(errorPath)}';`
    : ''

  const optionsEntries = [
    notFoundPath && 'notFoundComponent: NotFoundComponent',
    errorPath && 'errorComponent: ErrorComponent',
  ].filter(Boolean)
  const optionsArg = optionsEntries.length
    ? `, { ${optionsEntries.join(', ')} }`
    : ''

  const extraImports = [notFoundImport, errorImport].filter(Boolean).join('\n')

  return `// Auto-generated by @paretojs/core -- do not edit
import { startClient } from '@paretojs/core/client';
${allImports.join('\n')}
${extraImports ? extraImports + '\n' : ''}${cssImports.length > 0 ? '\n' + cssImports.join('\n') : ''}

${lazyImports.join('\n')}

const routes = [
${routeMap.join(',\n')}
];

startClient(routes${optionsArg});
`
}
